name: GitHub Readme Project Cards
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Profile Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Download Action Script
        run: |
          curl -O https://raw.githubusercontent.com/gnnrsc/github-readme-project-cards/main/action.py

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate Project Cards
        run: |
          python action.py \
            --github-username "gnnrsc" \
            --projects-config "projects-config.json" \
            --comment-tag-name "PROJECT-CARDS" \
            --output-only "false"

      - name: Commit and Push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Actions"
          author_email: "41898282+github-actions[bot]@users.noreply.github.com"
          message: "docs(readme): Auto-update Project cards"
          add: "."
          cwd: "."
